namespace QuantFlow.Common.Models;

/// <summary>
/// Represents a trading signal generated by an algorithm
/// </summary>
public class TradeSignalModel
{
    /// <summary>
    /// The trading action to take
    /// </summary>
    public TradeSignal Action { get; set; } = TradeSignal.Hold;

    /// <summary>
    /// Recommended entry price (null if holding)
    /// </summary>
    public decimal? EntryPrice { get; set; }

    /// <summary>
    /// Stop loss price level
    /// </summary>
    public decimal? StopLoss { get; set; }

    /// <summary>
    /// Take profit price level
    /// </summary>
    public decimal? TakeProfit { get; set; }

    /// <summary>
    /// Percentage of allocated capital to use (0-100)
    /// </summary>
    public decimal PositionSizePercent { get; set; } = 100m;

    /// <summary>
    /// Reason for this signal (for logging/debugging)
    /// </summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>
    /// Confidence level in this signal (0.0 to 1.0)
    /// </summary>
    public decimal Confidence { get; set; } = 0.5m;
}