namespace QuantFlow.Common.Enumerations;

/// <summary>
/// Represents the source/origin of a trading algorithm
/// </summary>
public enum AlgorithmSource
{
    /// <summary>
    /// Unknown or unspecified source
    /// </summary>
    Unknown = 0,

    /// <summary>
    /// Hard-coded algorithm built into the system
    /// </summary>
    HardCoded = 1,

    /// <summary>
    /// Custom algorithm written in C# by user
    /// </summary>
    CustomCSharp = 2,

    /// <summary>
    /// Custom algorithm written in Python by user
    /// </summary>
    CustomPython = 3,

    /// <summary>
    /// Algorithm generated by AI
    /// </summary>
    AIGenerated = 4
}