# .github/workflows/ci-cd.yaml
name: QuantFlow CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  HARBOR_REGISTRY: "10.47.1.106"
  HARBOR_PROJECT: "quantflow"
  IMAGE_NAME: "quantflow-datacollection"
  
jobs:
  build-test-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Verify .NET Installation
      run: |
        dotnet --version
        dotnet --list-sdks
    
    - name: Restore and Test
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
    
    - name: Login to Harbor
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ env.HARBOR_REGISTRY }} \
          --username "${{ secrets.HARBOR_USERNAME }}" --password-stdin
    
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        IMAGE_LATEST=${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:latest
        
        docker build -t $IMAGE_TAG -t $IMAGE_LATEST .
        docker push $IMAGE_TAG
        docker push $IMAGE_LATEST
    
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        
        IMAGE_TAG=${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
        # Deploy to development
        kubectl set image deployment/quantflow-datacollection \
          quantflow-datacollection=$IMAGE_TAG \
          -n development || \
        kubectl create deployment quantflow-datacollection \
          --image=$IMAGE_TAG \
          -n development
        
        # Wait for rollout
        kubectl rollout status deployment/quantflow-datacollection -n development
